export type Product = {
  id: string;
  slug: string;
  name: string;
  title: string;
  description: string;
  type: "tool" | "book" | "software" | "bundle";
  price: number;
  compareAtPrice?: number;
  currency: "VND" | "USD";
  domain: string;
  year: number;
  tags: string[];
  isHot?: boolean;
  isNew?: boolean;
  ratingAvg?: number;
  ratingCount?: number;
  thumbnail?: string;
  createdAt: string;
};
